name: Build Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'less version to build'
        required: true
        default: '581.2'

jobs:

  build-win32:

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Download version
      uses: actions/download-artifact@v2
      with:
        name: ver

    - name: Build the package
      run: |
        set LESS_VERSION=${{ github.event.inputs.version }}
        build.bat && 7z a less.7z less.exe lesskey.exe
      shell: cmd

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: less-win32
        path: less.7z
