name: Build Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'less version to build'
        required: true
        default: '581.2'

jobs:

  build-win32:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build the package
      run: |
        set LESS_VERSION=${{ github.event.inputs.version }}
        build.bat
      shell: cmd

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: less-exe
        path: less.exe

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: lesskey-exe
        path: lesskey.exe
